# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Youtube-stats Actions CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
    - run: npm install
    - run: npm run build --if-present
    
    steps:
  - uses: actions/checkout@v2
    name: Check out code

- name: Build & push Docker Image
  uses: mr-smithers-excellent/docker-build-push@v5
    with:
      image: tehliang/reactapp
      registry: docker.io
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
